config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  resources :posts do
    resources :comments
  end

  root "posts#index"

  get '/about', to: "pages#about"
   

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments, dependent: :destroy

    validates :title, presence: true, length: { minimum:5 }
    validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!, only: [:new]

    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(params[:comment].permit(:name, :body))

        redirect_to post_path(@post)
    end

    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy

        respond_to do |format|
            format.html { redirect_to post_path(@post), warning: 'Comentario Borrado' }
            format.json { head :no_content }
        end
    end

  

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def about
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :post_find, only: [:edit, :update, :show, :destroy]

    before_action :authenticate_user!, except: [:index, :show]

    def index
        @posts = Post.all
    end

    def show
    end

    def new
        @post = Post.new
        
    end

    def create
        @post = Post.new(post_params)

        respond_to do |format|
            if @post.save
              format.html { redirect_to @post, warning: 'Post Creado Exitosamente.' }
              format.json { render :show, status: :created, location: @post }
            else
              format.html { render :new }
              format.json { render json: @post.errors, status: :unprocessable_entity }
            end
        end
    end

    def update
        respond_to do |format|
            if @post.update(post_params)
              format.html { redirect_to @post, warning: 'Post Editado Exitosamente.' }
              format.json { render :show, status: :ok, location: @post }
            else
              format.html { render :edit }
              format.json { render json: @post.errors, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        @post.destroy
            respond_to do |format|
                format.html { redirect_to posts_url, warning: 'Post Borrado Exitosamente.' }
                format.json { head :no_content }
        end
    end

    def post_find
        @post = Post.find(params[:id])

    end

    private
        def post_params
            params.require(:post).permit(:title, :body)
        end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
    <div class="comment_content">
        <p class="comment_name"><strong><%= comment.name %></strong></p>
        <p class="comment_body"><%= comment.body%></p>
        <p class="comment_title"><%= time_ago_in_words(comment.created_at)%></p>
    </div>
    <% if user_signed_in? %>
        <p><%= link_to "Borrar Comentario", [comment.post, comment], method: :delete, class: "button", data: {confirm: "Estas Seguro?"} %></p>
    <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
    <p>
        <%= f.label :name%><br>
        <%= f.text_field :name %>
    </p>

    <p>
        <%= f.label :body%><br>
        <%= f.text_field :body %>
    </p>

    <p>
        <%= f.submit%>
    </p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tumblr Rails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Raleway:400,700" rel="stylesheet'%>
  </head>

  <body>
    <div id="sidebar">
      <%= render "partials/sidebar"%>
    </div>

    <div id="main_content">
      <%= render "partials/header"%>
      <%= render "partials/notificaciones"%>
      <%= yield %>
    </div>
    
    
  </body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
    <div id="profile_image">
        <%= image_tag "profile.jpeg" %>
    </div>

    <div id="content">
        <h1>Este Es Mr Loco</h1>
        <p> is simply dummy text of the printing and typesetting industry. 
        Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
        when an unknown printer took a galley of type and scrambled it to make a type specimen book. 
        It has survived not only five centuries, but also the leap into electronic typesetting, 
        remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, 
        and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum
        </p>
    </div>
</div>

app/views/partials/_header.html.erb
<div id="header">
    <% if current_page?(root_path) %>
        <p>Post Feed</p>
    <% elsif current_page?(about_path) %>
        <p>Mi Sitio</p>
    <% else %>
        <%= link_to "Volver A Post Feed", root_path %>
    <% end %>
    <% if user_signed_in? %>
        <div class="buttons">
            <button class="button"><%= link_to "Crear Post", new_post_path%></button>
            <button class="button"><%= link_to "Desloguearse", destroy_user_session_path, :method => :delete %></button>
        </div>
    <% end %>
</div>

app/views/partials/_notificaciones.html.erb
<% flash.each do |name, msg| %>
        <div class="alert alert-dismissible alert-<%= name %>">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <h4 class="alert-heading"><%= msg %></h4>
        </div>
      <%end%>

app/views/partials/_sidebar.html.erb
<ul>
    <li class="category"><%= link_to "Tumblr", root_path %></li>
    <li><%= link_to "Posts", root_path %></li>
    <li><%= link_to "Sobre", about_path %> </li>
</ul>
    <% if !user_signed_in? %>
        <p class="sign_in"><%= link_to "Iniciar Sesion", new_user_session_path %></p>
    <% end %>
    

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
        <% if @post.errors.any? %>
            <div id="errors">
                <h2><%= pluralize(@post.errors.count, "error")%> Post No Puede Ser Guardado</h2>
                <ul>
                    <% @post.errors.full_messages.each do |msg|%>
                    <li><%= msg %></li>
                    <% end %>
                </ul>
            </div>

        <% end %>
        <p>
            <%= f.label "Titulo:" %>
            <%= f.text_field :title %>
        
        </p>
            <%= f.label "Cuerpo:" %>
            <%= f.text_area :body %>

        <p>
        
        </p>
            
            <%= f.submit %>

        <p>
        
        </p>
    <% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
    <h1>Editar Post</h1>

    <%= render "form" %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post|%>
    <div class="post_wrapper">
        <h2 class="title"><%= link_to post.title, post %></h2>
        <p class="body"><%= truncate(post.body, lenth:100) %></p>
        <p class="date"><%= time_ago_in_words(post.created_at) %></p>
    </div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
    <h1>Nuevo Post</h1>

    <%= render "form" %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
    <h1 class="title">
        <%= @post.title %>
    </h1>

    <p class="date">
        Enviado <%= time_ago_in_words(@post.created_at) %> |
        <% if user_signed_in? %>
            <%= link_to "Editar", edit_post_path(@post)%> |
            <%= link_to "Eliminar", post_path(@post), method: :delete, data: {confirm: "Estas Seguro" }%>
        <% end %>

    </p>

    <p class="body">
        <%= @post.body %>
    </p>

    <div id="comments">
        <h2><%= @post.comments.count %> Comentarios</h2>
        <%= render @post.comments %>
        <h3>Comentar: </h3>
        <%= render "comments/form" %>
    </div>
</div>